### ISSUE TITLE
Full Data Availabel?

### ISSUE THREAD

**Issue by adrian-jaques-b** [pierpaologoffredo/Counter-TWIT#1]
Hello,
Thank you for sharing your work with the community. I am currently researching counter-speech recognition in German and find your approach very interesting and helpful!
However, I wanted to ask, since you used whole conversations for classification: In what format did you save/collected them? (Root & Reply Tweets)
Is this data available somewhere?
Another question I have is if I can get the entire annotated data somewhere? 
Sorry if it is written somewhere and I missed it (I don't speak Italian).
Thank you very much!

Regards,
Jaqu

**Comment by pierpaologoffredo** [comment]
Hello @JaquJaqu !
Sorry for the late reply. 
Anyway, you can read the paper about this work on this [link](https://www.researchgate.net/publication/362260356_Counter-TWIT_An_Italian_Corpus_for_Online_Counterspeech_in_Ecological_Contexts) where I explain that I made this corpus using the Twitter API for collecting the tweets in JSON format. After that I processed all the files in order to create the [current corpus](https://github.com/pierpaologoffredo/Counter-TWIT/blob/main/counter_twit_corpus.csv). I think I answered to all the question you made. If not, don't esithate to contact me again!

Thank you for your interest!

Regards,
Pierpaolo

**Comment by adrian-jaques-b** [comment]
Hello, 
No problem, I am very busy myself these days :)
I think I got it now. Thank you so much for you help!

Regards,
Jaqu
